// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"base-frame/common/model"
)

func newMsgFriendCount1(db *gorm.DB, opts ...gen.DOOption) msgFriendCount1 {
	_msgFriendCount1 := msgFriendCount1{}

	_msgFriendCount1.msgFriendCount1Do.UseDB(db, opts...)
	_msgFriendCount1.msgFriendCount1Do.UseModel(&model.MsgFriendCount1{})

	tableName := _msgFriendCount1.msgFriendCount1Do.TableName()
	_msgFriendCount1.ALL = field.NewAsterisk(tableName)
	_msgFriendCount1.ID = field.NewUint64(tableName, "id")
	_msgFriendCount1.UID = field.NewUint32(tableName, "uid")
	_msgFriendCount1.Sum = field.NewUint32(tableName, "sum")
	_msgFriendCount1.Unread = field.NewUint32(tableName, "unread")
	_msgFriendCount1.CreateTime = field.NewUint32(tableName, "create_time")
	_msgFriendCount1.UpdateTime = field.NewUint32(tableName, "update_time")

	_msgFriendCount1.fillFieldMap()

	return _msgFriendCount1
}

type msgFriendCount1 struct {
	msgFriendCount1Do msgFriendCount1Do

	ALL        field.Asterisk
	ID         field.Uint64
	UID        field.Uint32 // 用户id
	Sum        field.Uint32 // 总数
	Unread     field.Uint32 // 未读数量
	CreateTime field.Uint32 // 创建时间
	UpdateTime field.Uint32 // 更新时间

	fieldMap map[string]field.Expr
}

func (m msgFriendCount1) Table(newTableName string) *msgFriendCount1 {
	m.msgFriendCount1Do.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m msgFriendCount1) As(alias string) *msgFriendCount1 {
	m.msgFriendCount1Do.DO = *(m.msgFriendCount1Do.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *msgFriendCount1) updateTableName(table string) *msgFriendCount1 {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.UID = field.NewUint32(table, "uid")
	m.Sum = field.NewUint32(table, "sum")
	m.Unread = field.NewUint32(table, "unread")
	m.CreateTime = field.NewUint32(table, "create_time")
	m.UpdateTime = field.NewUint32(table, "update_time")

	m.fillFieldMap()

	return m
}

func (m *msgFriendCount1) WithContext(ctx context.Context) *msgFriendCount1Do {
	return m.msgFriendCount1Do.WithContext(ctx)
}

func (m msgFriendCount1) TableName() string { return m.msgFriendCount1Do.TableName() }

func (m msgFriendCount1) Alias() string { return m.msgFriendCount1Do.Alias() }

func (m *msgFriendCount1) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *msgFriendCount1) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["id"] = m.ID
	m.fieldMap["uid"] = m.UID
	m.fieldMap["sum"] = m.Sum
	m.fieldMap["unread"] = m.Unread
	m.fieldMap["create_time"] = m.CreateTime
	m.fieldMap["update_time"] = m.UpdateTime
}

func (m msgFriendCount1) clone(db *gorm.DB) msgFriendCount1 {
	m.msgFriendCount1Do.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m msgFriendCount1) replaceDB(db *gorm.DB) msgFriendCount1 {
	m.msgFriendCount1Do.ReplaceDB(db)
	return m
}

type msgFriendCount1Do struct{ gen.DO }

func (m msgFriendCount1Do) Debug() *msgFriendCount1Do {
	return m.withDO(m.DO.Debug())
}

func (m msgFriendCount1Do) WithContext(ctx context.Context) *msgFriendCount1Do {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m msgFriendCount1Do) ReadDB() *msgFriendCount1Do {
	return m.Clauses(dbresolver.Read)
}

func (m msgFriendCount1Do) WriteDB() *msgFriendCount1Do {
	return m.Clauses(dbresolver.Write)
}

func (m msgFriendCount1Do) Session(config *gorm.Session) *msgFriendCount1Do {
	return m.withDO(m.DO.Session(config))
}

func (m msgFriendCount1Do) Clauses(conds ...clause.Expression) *msgFriendCount1Do {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m msgFriendCount1Do) Returning(value interface{}, columns ...string) *msgFriendCount1Do {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m msgFriendCount1Do) Not(conds ...gen.Condition) *msgFriendCount1Do {
	return m.withDO(m.DO.Not(conds...))
}

func (m msgFriendCount1Do) Or(conds ...gen.Condition) *msgFriendCount1Do {
	return m.withDO(m.DO.Or(conds...))
}

func (m msgFriendCount1Do) Select(conds ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.Select(conds...))
}

func (m msgFriendCount1Do) Where(conds ...gen.Condition) *msgFriendCount1Do {
	return m.withDO(m.DO.Where(conds...))
}

func (m msgFriendCount1Do) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *msgFriendCount1Do {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m msgFriendCount1Do) Order(conds ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.Order(conds...))
}

func (m msgFriendCount1Do) Distinct(cols ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m msgFriendCount1Do) Omit(cols ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.Omit(cols...))
}

func (m msgFriendCount1Do) Join(table schema.Tabler, on ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.Join(table, on...))
}

func (m msgFriendCount1Do) LeftJoin(table schema.Tabler, on ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m msgFriendCount1Do) RightJoin(table schema.Tabler, on ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m msgFriendCount1Do) Group(cols ...field.Expr) *msgFriendCount1Do {
	return m.withDO(m.DO.Group(cols...))
}

func (m msgFriendCount1Do) Having(conds ...gen.Condition) *msgFriendCount1Do {
	return m.withDO(m.DO.Having(conds...))
}

func (m msgFriendCount1Do) Limit(limit int) *msgFriendCount1Do {
	return m.withDO(m.DO.Limit(limit))
}

func (m msgFriendCount1Do) Offset(offset int) *msgFriendCount1Do {
	return m.withDO(m.DO.Offset(offset))
}

func (m msgFriendCount1Do) Scopes(funcs ...func(gen.Dao) gen.Dao) *msgFriendCount1Do {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m msgFriendCount1Do) Unscoped() *msgFriendCount1Do {
	return m.withDO(m.DO.Unscoped())
}

func (m msgFriendCount1Do) Create(values ...*model.MsgFriendCount1) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m msgFriendCount1Do) CreateInBatches(values []*model.MsgFriendCount1, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m msgFriendCount1Do) Save(values ...*model.MsgFriendCount1) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m msgFriendCount1Do) First() (*model.MsgFriendCount1, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendCount1), nil
	}
}

func (m msgFriendCount1Do) Take() (*model.MsgFriendCount1, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendCount1), nil
	}
}

func (m msgFriendCount1Do) Last() (*model.MsgFriendCount1, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendCount1), nil
	}
}

func (m msgFriendCount1Do) Find() ([]*model.MsgFriendCount1, error) {
	result, err := m.DO.Find()
	return result.([]*model.MsgFriendCount1), err
}

func (m msgFriendCount1Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MsgFriendCount1, err error) {
	buf := make([]*model.MsgFriendCount1, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m msgFriendCount1Do) FindInBatches(result *[]*model.MsgFriendCount1, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m msgFriendCount1Do) Attrs(attrs ...field.AssignExpr) *msgFriendCount1Do {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m msgFriendCount1Do) Assign(attrs ...field.AssignExpr) *msgFriendCount1Do {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m msgFriendCount1Do) Joins(fields ...field.RelationField) *msgFriendCount1Do {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m msgFriendCount1Do) Preload(fields ...field.RelationField) *msgFriendCount1Do {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m msgFriendCount1Do) FirstOrInit() (*model.MsgFriendCount1, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendCount1), nil
	}
}

func (m msgFriendCount1Do) FirstOrCreate() (*model.MsgFriendCount1, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendCount1), nil
	}
}

func (m msgFriendCount1Do) FindByPage(offset int, limit int) (result []*model.MsgFriendCount1, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m msgFriendCount1Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m msgFriendCount1Do) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m msgFriendCount1Do) Delete(models ...*model.MsgFriendCount1) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *msgFriendCount1Do) withDO(do gen.Dao) *msgFriendCount1Do {
	m.DO = *do.(*gen.DO)
	return m
}
