// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"base-frame/common/model"
)

func newMsgFriendMsg(db *gorm.DB, opts ...gen.DOOption) msgFriendMsg {
	_msgFriendMsg := msgFriendMsg{}

	_msgFriendMsg.msgFriendMsgDo.UseDB(db, opts...)
	_msgFriendMsg.msgFriendMsgDo.UseModel(&model.MsgFriendMsg{})

	tableName := _msgFriendMsg.msgFriendMsgDo.TableName()
	_msgFriendMsg.ALL = field.NewAsterisk(tableName)
	_msgFriendMsg.ID = field.NewUint64(tableName, "id")
	_msgFriendMsg.UID = field.NewUint32(tableName, "uid")
	_msgFriendMsg.FromUID = field.NewUint32(tableName, "from_uid")
	_msgFriendMsg.FromAvatar = field.NewString(tableName, "from_avatar")
	_msgFriendMsg.FromUsername = field.NewString(tableName, "from_username")
	_msgFriendMsg.FromDomain = field.NewString(tableName, "from_domain")
	_msgFriendMsg.Content = field.NewString(tableName, "content")
	_msgFriendMsg.Status = field.NewUint8(tableName, "status")
	_msgFriendMsg.CreateTime = field.NewUint32(tableName, "create_time")
	_msgFriendMsg.UpdateTime = field.NewUint32(tableName, "update_time")
	_msgFriendMsg.OriginID = field.NewString(tableName, "origin_id")

	_msgFriendMsg.fillFieldMap()

	return _msgFriendMsg
}

type msgFriendMsg struct {
	msgFriendMsgDo msgFriendMsgDo

	ALL          field.Asterisk
	ID           field.Uint64
	UID          field.Uint32 // 用户id
	FromUID      field.Uint32 // 发送者用户id
	FromAvatar   field.String // 头像
	FromUsername field.String // 发送者用户名
	FromDomain   field.String // 个性化域名
	Content      field.String // 内容
	Status       field.Uint8  // 0未读 1已读
	CreateTime   field.Uint32 // 创建时间
	UpdateTime   field.Uint32 // 更新时间
	OriginID     field.String // 原始id

	fieldMap map[string]field.Expr
}

func (m msgFriendMsg) Table(newTableName string) *msgFriendMsg {
	m.msgFriendMsgDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m msgFriendMsg) As(alias string) *msgFriendMsg {
	m.msgFriendMsgDo.DO = *(m.msgFriendMsgDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *msgFriendMsg) updateTableName(table string) *msgFriendMsg {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.UID = field.NewUint32(table, "uid")
	m.FromUID = field.NewUint32(table, "from_uid")
	m.FromAvatar = field.NewString(table, "from_avatar")
	m.FromUsername = field.NewString(table, "from_username")
	m.FromDomain = field.NewString(table, "from_domain")
	m.Content = field.NewString(table, "content")
	m.Status = field.NewUint8(table, "status")
	m.CreateTime = field.NewUint32(table, "create_time")
	m.UpdateTime = field.NewUint32(table, "update_time")
	m.OriginID = field.NewString(table, "origin_id")

	m.fillFieldMap()

	return m
}

func (m *msgFriendMsg) WithContext(ctx context.Context) *msgFriendMsgDo {
	return m.msgFriendMsgDo.WithContext(ctx)
}

func (m msgFriendMsg) TableName() string { return m.msgFriendMsgDo.TableName() }

func (m msgFriendMsg) Alias() string { return m.msgFriendMsgDo.Alias() }

func (m *msgFriendMsg) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *msgFriendMsg) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["uid"] = m.UID
	m.fieldMap["from_uid"] = m.FromUID
	m.fieldMap["from_avatar"] = m.FromAvatar
	m.fieldMap["from_username"] = m.FromUsername
	m.fieldMap["from_domain"] = m.FromDomain
	m.fieldMap["content"] = m.Content
	m.fieldMap["status"] = m.Status
	m.fieldMap["create_time"] = m.CreateTime
	m.fieldMap["update_time"] = m.UpdateTime
	m.fieldMap["origin_id"] = m.OriginID
}

func (m msgFriendMsg) clone(db *gorm.DB) msgFriendMsg {
	m.msgFriendMsgDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m msgFriendMsg) replaceDB(db *gorm.DB) msgFriendMsg {
	m.msgFriendMsgDo.ReplaceDB(db)
	return m
}

type msgFriendMsgDo struct{ gen.DO }

func (m msgFriendMsgDo) Debug() *msgFriendMsgDo {
	return m.withDO(m.DO.Debug())
}

func (m msgFriendMsgDo) WithContext(ctx context.Context) *msgFriendMsgDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m msgFriendMsgDo) ReadDB() *msgFriendMsgDo {
	return m.Clauses(dbresolver.Read)
}

func (m msgFriendMsgDo) WriteDB() *msgFriendMsgDo {
	return m.Clauses(dbresolver.Write)
}

func (m msgFriendMsgDo) Session(config *gorm.Session) *msgFriendMsgDo {
	return m.withDO(m.DO.Session(config))
}

func (m msgFriendMsgDo) Clauses(conds ...clause.Expression) *msgFriendMsgDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m msgFriendMsgDo) Returning(value interface{}, columns ...string) *msgFriendMsgDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m msgFriendMsgDo) Not(conds ...gen.Condition) *msgFriendMsgDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m msgFriendMsgDo) Or(conds ...gen.Condition) *msgFriendMsgDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m msgFriendMsgDo) Select(conds ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m msgFriendMsgDo) Where(conds ...gen.Condition) *msgFriendMsgDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m msgFriendMsgDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *msgFriendMsgDo {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m msgFriendMsgDo) Order(conds ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m msgFriendMsgDo) Distinct(cols ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m msgFriendMsgDo) Omit(cols ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m msgFriendMsgDo) Join(table schema.Tabler, on ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m msgFriendMsgDo) LeftJoin(table schema.Tabler, on ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m msgFriendMsgDo) RightJoin(table schema.Tabler, on ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m msgFriendMsgDo) Group(cols ...field.Expr) *msgFriendMsgDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m msgFriendMsgDo) Having(conds ...gen.Condition) *msgFriendMsgDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m msgFriendMsgDo) Limit(limit int) *msgFriendMsgDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m msgFriendMsgDo) Offset(offset int) *msgFriendMsgDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m msgFriendMsgDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *msgFriendMsgDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m msgFriendMsgDo) Unscoped() *msgFriendMsgDo {
	return m.withDO(m.DO.Unscoped())
}

func (m msgFriendMsgDo) Create(values ...*model.MsgFriendMsg) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m msgFriendMsgDo) CreateInBatches(values []*model.MsgFriendMsg, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m msgFriendMsgDo) Save(values ...*model.MsgFriendMsg) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m msgFriendMsgDo) First() (*model.MsgFriendMsg, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendMsg), nil
	}
}

func (m msgFriendMsgDo) Take() (*model.MsgFriendMsg, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendMsg), nil
	}
}

func (m msgFriendMsgDo) Last() (*model.MsgFriendMsg, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendMsg), nil
	}
}

func (m msgFriendMsgDo) Find() ([]*model.MsgFriendMsg, error) {
	result, err := m.DO.Find()
	return result.([]*model.MsgFriendMsg), err
}

func (m msgFriendMsgDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MsgFriendMsg, err error) {
	buf := make([]*model.MsgFriendMsg, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m msgFriendMsgDo) FindInBatches(result *[]*model.MsgFriendMsg, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m msgFriendMsgDo) Attrs(attrs ...field.AssignExpr) *msgFriendMsgDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m msgFriendMsgDo) Assign(attrs ...field.AssignExpr) *msgFriendMsgDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m msgFriendMsgDo) Joins(fields ...field.RelationField) *msgFriendMsgDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m msgFriendMsgDo) Preload(fields ...field.RelationField) *msgFriendMsgDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m msgFriendMsgDo) FirstOrInit() (*model.MsgFriendMsg, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendMsg), nil
	}
}

func (m msgFriendMsgDo) FirstOrCreate() (*model.MsgFriendMsg, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MsgFriendMsg), nil
	}
}

func (m msgFriendMsgDo) FindByPage(offset int, limit int) (result []*model.MsgFriendMsg, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m msgFriendMsgDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m msgFriendMsgDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m msgFriendMsgDo) Delete(models ...*model.MsgFriendMsg) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *msgFriendMsgDo) withDO(do gen.Dao) *msgFriendMsgDo {
	m.DO = *do.(*gen.DO)
	return m
}
