// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMsgSubTask = "msg_sub_task"

// MsgSubTask mapped from table <msg_sub_task>
type MsgSubTask struct {
	ID         uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" mapstructure:"id"`
	TaskID     uint32         `gorm:"column:task_id;not null;index:idx_task_id,priority:1" json:"task_id" mapstructure:"task_id"` // 任务id
	TemplateID uint32         `gorm:"column:template_id;not null" json:"template_id" mapstructure:"template_id"`                  // 模版id
	Status     int8           `gorm:"column:status;not null" json:"status" mapstructure:"status"`                                 // 任务状态： 0-启用 1-停用
	Creator    string         `gorm:"column:creator;not null" json:"creator" mapstructure:"creator"`                              // 创建人
	CreatedAt  time.Time      `gorm:"column:created_at;not null" json:"created_at" mapstructure:"created_at"`                     // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null" json:"updated_at" mapstructure:"updated_at"`                     // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at" mapstructure:"deleted_at"`                              // 删除时间
}

// TableName MsgSubTask's table name
func (*MsgSubTask) TableName() string {
	return TableNameMsgSubTask
}
