// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMsgFriendMsg = "msg_friend_msg"

// MsgFriendMsg mapped from table <msg_friend_msg>
type MsgFriendMsg struct {
	ID           uint64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" mapstructure:"id"`
	UID          uint32 `gorm:"column:uid;primaryKey;index:idx_uid_create_time_status_mfm,priority:1;uniqueIndex:uniq_uid_orgin_id_mfm,priority:2" json:"uid" mapstructure:"uid"` // 用户id
	FromUID      uint32 `gorm:"column:from_uid;not null" json:"from_uid" mapstructure:"from_uid"`                                                                                 // 发送者用户id
	FromAvatar   string `gorm:"column:from_avatar;not null" json:"from_avatar" mapstructure:"from_avatar"`                                                                        // 头像
	FromUsername string `gorm:"column:from_username;not null" json:"from_username" mapstructure:"from_username"`                                                                  // 发送者用户名
	FromDomain   string `gorm:"column:from_domain;not null" json:"from_domain" mapstructure:"from_domain"`                                                                        // 个性化域名
	Content      string `gorm:"column:content;not null" json:"content" mapstructure:"content"`                                                                                    // 内容
	Status       uint8  `gorm:"column:status;not null;index:idx_uid_create_time_status_mfm,priority:3" json:"status" mapstructure:"status"`                                       // 0未读 1已读
	CreateTime   uint32 `gorm:"column:create_time;not null;index:idx_uid_create_time_status_mfm,priority:2" json:"create_time" mapstructure:"create_time"`                        // 创建时间
	UpdateTime   uint32 `gorm:"column:update_time;not null;index:idx_update_time_mfm,priority:1" json:"update_time" mapstructure:"update_time"`                                   // 更新时间
	OriginID     string `gorm:"column:origin_id;not null;uniqueIndex:uniq_uid_orgin_id_mfm,priority:1" json:"origin_id" mapstructure:"origin_id"`                                 // 原始id
}

// TableName MsgFriendMsg's table name
func (*MsgFriendMsg) TableName() string {
	return TableNameMsgFriendMsg
}
