// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMsgTemplate = "msg_template"

// MsgTemplate mapped from table <msg_template>
type MsgTemplate struct {
	ID              uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" mapstructure:"id"`
	AccountTag      string         `gorm:"column:account_tag;not null;uniqueIndex:idx_account_tag_template_id,priority:1" json:"account_tag" mapstructure:"account_tag"`                                                          // 第三方账号id
	Channel         string         `gorm:"column:channel;not null;index:idx_channel,priority:1" json:"channel" mapstructure:"channel"`                                                                                            // 渠道 sms email app dingtalk sysmsg pcpush
	ThirdTemplateID string         `gorm:"column:third_template_id;not null;uniqueIndex:idx_account_tag_template_id,priority:2;index:idx_third_template_id,priority:1" json:"third_template_id" mapstructure:"third_template_id"` // 第三方模版id
	Name            string         `gorm:"column:name;not null" json:"name" mapstructure:"name"`                                                                                                                                  // 模版名称
	Content         string         `gorm:"column:content;not null" json:"content" mapstructure:"content"`                                                                                                                         // 模版内容
	Params          string         `gorm:"column:params" json:"params" mapstructure:"params"`                                                                                                                                     // 请求参数模版
	Remark          string         `gorm:"column:remark;not null" json:"remark" mapstructure:"remark"`                                                                                                                            // 模版备注
	ThirdStatus     int8           `gorm:"column:third_status;not null" json:"third_status" mapstructure:"third_status"`                                                                                                          // 第三方状态 1-申请中 2-申请成功 3 申请驳回
	Type            int8           `gorm:"column:type;not null" json:"type" mapstructure:"type"`                                                                                                                                  // 模版类型：0-验证码1-通知 2-营销
	Status          int8           `gorm:"column:status;not null" json:"status" mapstructure:"status"`                                                                                                                            // 任务状态： 0-启用 1-停用
	Creator         string         `gorm:"column:creator;not null" json:"creator" mapstructure:"creator"`                                                                                                                         // 创建人
	CreatedAt       time.Time      `gorm:"column:created_at;not null" json:"created_at" mapstructure:"created_at"`                                                                                                                // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null" json:"updated_at" mapstructure:"updated_at"`                                                                                                                // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at" mapstructure:"deleted_at"`                                                                                                                         // 删除时间
}

// TableName MsgTemplate's table name
func (*MsgTemplate) TableName() string {
	return TableNameMsgTemplate
}
