// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMsgAccount = "msg_account"

// MsgAccount mapped from table <msg_account>
type MsgAccount struct {
	ID        uint32         `gorm:"column:id;primaryKey" json:"id" mapstructure:"id"`
	Tag       string         `gorm:"column:tag;not null;index:uniq_tag,priority:1" json:"tag" mapstructure:"tag"`            // 账号标识
	Name      string         `gorm:"column:name;not null" json:"name" mapstructure:"name"`                                   // 账号名称
	Remark    string         `gorm:"column:remark;not null" json:"remark" mapstructure:"remark"`                             // 账号备注
	Vendor    string         `gorm:"column:vendor;not null;index:idx_vendor,priority:1" json:"vendor" mapstructure:"vendor"` // 厂商
	Config    string         `gorm:"column:config" json:"config" mapstructure:"config"`                                      // 账号配置
	Status    int8           `gorm:"column:status;not null" json:"status" mapstructure:"status"`                             // 任务状态： 0-启用 1-停用
	Creator   string         `gorm:"column:creator;not null" json:"creator" mapstructure:"creator"`                          // 创建人
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at" mapstructure:"created_at"`                 // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at" mapstructure:"updated_at"`                 // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at" mapstructure:"deleted_at"`                          // 删除时间
}

// TableName MsgAccount's table name
func (*MsgAccount) TableName() string {
	return TableNameMsgAccount
}
