// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMsgSysMsg = "msg_sys_msg"

// MsgSysMsg mapped from table <msg_sys_msg>
type MsgSysMsg struct {
	ID          uint64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" mapstructure:"id"`
	Title       string `gorm:"column:title;not null" json:"title" mapstructure:"title"`                                                                                          // 标题
	Content     string `gorm:"column:content;not null" json:"content" mapstructure:"content"`                                                                                    // 内容
	UID         uint32 `gorm:"column:uid;primaryKey;index:idx_uid_create_time_status_msm,priority:1;uniqueIndex:uniq_uid_orgin_id_msm,priority:2" json:"uid" mapstructure:"uid"` // 用户id
	Role        uint32 `gorm:"column:role;not null" json:"role" mapstructure:"role"`                                                                                             // 来源
	Extras      string `gorm:"column:extras" json:"extras" mapstructure:"extras"`                                                                                                // 扩展数据
	Extra       string `gorm:"column:extra;not null" json:"extra" mapstructure:"extra"`                                                                                          // 预留
	Avatar      string `gorm:"column:avatar;not null" json:"avatar" mapstructure:"avatar"`                                                                                       // 预留
	JumpPage    string `gorm:"column:jump_page;not null" json:"jump_page" mapstructure:"jump_page"`                                                                              // 预留
	MessageMode uint32 `gorm:"column:message_mode;not null" json:"message_mode" mapstructure:"message_mode"`                                                                     // 预留
	Status      uint8  `gorm:"column:status;not null;index:idx_uid_create_time_status_msm,priority:3" json:"status" mapstructure:"status"`                                       // 0未读 1已读
	CreateTime  uint32 `gorm:"column:create_time;not null;index:idx_uid_create_time_status_msm,priority:2" json:"create_time" mapstructure:"create_time"`                        // 创建时间
	UpdateTime  uint32 `gorm:"column:update_time;not null;index:idx_update_time_msm,priority:1" json:"update_time" mapstructure:"update_time"`                                   // 更新时间
	OriginID    string `gorm:"column:origin_id;not null;uniqueIndex:uniq_uid_orgin_id_msm,priority:1" json:"origin_id" mapstructure:"origin_id"`                                 // 原始id
}

// TableName MsgSysMsg's table name
func (*MsgSysMsg) TableName() string {
	return TableNameMsgSysMsg
}
