// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMsgTask = "msg_task"

// MsgTask mapped from table <msg_task>
type MsgTask struct {
	ID        uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id" mapstructure:"id"`
	Name      string         `gorm:"column:name;not null" json:"name" mapstructure:"name"`                                  // 任务名称
	Code      string         `gorm:"column:code;not null;uniqueIndex:uniq_code,priority:1" json:"code" mapstructure:"code"` // 任务码
	Params    string         `gorm:"column:params" json:"params" mapstructure:"params"`                                     // 任务参数
	Type      int8           `gorm:"column:type;not null" json:"type" mapstructure:"type"`                                  // 任务类型：0-系统发送 1-人工发送
	Status    int8           `gorm:"column:status;not null" json:"status" mapstructure:"status"`                            // 任务状态： 0-启用 1-停用
	Creator   string         `gorm:"column:creator;not null" json:"creator" mapstructure:"creator"`                         // 创建人
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at" mapstructure:"created_at"`                // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at" mapstructure:"updated_at"`                // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at" mapstructure:"deleted_at"`                         // 删除时间
}

// TableName MsgTask's table name
func (*MsgTask) TableName() string {
	return TableNameMsgTask
}
