apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-multi-gin
  labels:
    app: foo-multi-gin
spec:
  selector:
    matchLabels:
      app: foo-multi-gin
  template:
    metadata:
      labels:
        log: "true"
        app: foo-multi-gin
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - foo-multi-gin
          # requiredDuringSchedulingIgnoredDuringExecution:
          #   - labelSelector:
          #     matchExpressions:
          #       - key: app
          #         operator: In
          #         values:
          #           - foo-multi-gin
          #     topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 120
      containers:
        - name: foo-multi-gin
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
                - "/app/foo-multi-gin"
                - liveness
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - "/app/foo-multi-gin"
                - readiness
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep","30"]
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "1000Mi"
              cpu: "2000m"
          envFrom:
            - configMapRef:
                name: gowins-env
          volumeMounts:
            - name: gowins-volume
              mountPath: app/etc
      volumes:
        - name: gowins-volume
          configMap:
            name: foo-multi-gin-conf
      imagePullSecrets:
        - name: ggdata-dev

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: foo-multi-gin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foo-multi-gin
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 800Mi

---
apiVersion: v1
kind: Service
metadata:
  name: foo-multi-gin
  labels:
    app: foo-multi-gin
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: foo-multi-gin
