// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/gowins/dionysus/ginx"
)

func RegisterHandlers(gr ginx.ZeroGinRouter) {
	adminv1Group := gr.Group("admin/v1")
	adminv1Group.Use(ginx.TimeoutMiddleware(1000))
	adminv1Group.Use(ginx.LimiterMiddleware(1000))
	adminv1Group.Handle(http.MethodPost, "/task/list", taskv1.List)
	adminv1Group.Handle(http.MethodPost, "/task/get", taskv1.List)
}
