// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"book/service/user/api/internal/svc"
	foov1 "book/service/user/api/internal/handler/foo/v1"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	[]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/user/login",
			Handler: foov1.LoginHandler(serverCtx),
		},
},
}
