// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Number     string    `gorm:"column:number;not null" json:"number"`     // 学号
	Name       string    `gorm:"column:name;not null" json:"name"`         // 用户名称
	Password   string    `gorm:"column:password;not null" json:"password"` // 用户密码
	Gender     string    `gorm:"column:gender;not null" json:"gender"`     // 男｜女｜未公开
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
